<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="block <?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>">
    <div class="title <?php /* @escapeNotVerified */ echo $block->getBlockCss();?>-title">
        <strong><?php /* @escapeNotVerified */ echo __('My Auction Information'); ?></strong>
    </div>
    <div class="content <?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>-content" id="<?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>
