<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $this Magento\Catalog\Block\Product\View
 * @var $auction Magestore\Auction\Model\Auction
 */
?>
<div id="auction" data-mage-init='{"magestore/auction": {
                                        "url":"<?php echo $this->getUrl('auction/index/createAuctionBox',array('_secure'=>true)) ?>",
                                        "product_id":"<?php echo $this->getProduct()->getId() ?>"
                                    }}'></div>